pedido/urls.py
from django.urls import path, include
from .views import PagarPedido, DetalhePedido, FinalizarPedido, ListaPedido

urlpatterns = [
    path("pagar-perdido/<int:pk>/", PagarPedido.as_view(), name="pagar-pedido"),
    path("finalizar-pedido/", FinalizarPedido.as_view(), name="finalizar-pedido"),
    path("detalhe-pedido/<int:pk>/", DetalhePedido.as_view(), name="detalhe-pedido"),
    path("lista-pedido/", ListaPedido.as_view(), name="lista-pedido"),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
import re

class Pedido(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField() 
    status = models.CharField(
        default="C",
        max_length=50,
        choices=(
            ("A","Aprovado"),
            ("C","Criado"),
            ("R","Reprovado"),
            ("P","Pendente"),
            ("E","Enviado"),
            ("F","Finalizado"),
        )
    )


class ItemPedido(models.Model):
    id_produto = models.IntegerField(primary_key=True,blank=False,null=False)
    pedido = models.ForeignKey(Pedido,on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    variacao = models.CharField(max_length=255)
    id_variacao = models.IntegerField()
    preco = models.FloatField()
    preco_promo = models.FloatField(default=0)
    quantidade = models.IntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f"Número pedido {self.pk}"

    class Meta:
        verbose_name = "Item do Pedido"
        verbose_name_plural = "Itens do Pedido"

pedido/views.py
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from produto.models import Variacao
from .models import Pedido, ItemPedido



class DispatchLoginRequiredMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect(reverse_lazy("login"))

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)
         

class PagarPedido(DispatchLoginRequiredMixin, DetailView):
    template_name = "pedido/pagar_pedido.html"
    model = Pedido
    pk_url_kwarg = "pk" 
    context_object_name = "pedido"
    

class FinalizarPedido(View):
    template_name = "pedido/pagar_pedido.html"
    @method_decorator(login_required(login_url='/login/'))  
    def get(self,*args,**kwargs):

        if not self.request.session.get("carrinho"):
            messages.error(
                self.request,
                "Seu carrinho está vazio."
            )
            return redirect(reverse_lazy("listagem-produto"))
        
        estoque_insuficiente = False
        dict_pagar = {}

        carrinho = self.request.session.get("carrinho")
        carrinho_id = [variacao for variacao in carrinho]
        variacoes = list(Variacao.objects.select_related("produto").filter(id__in=carrinho_id))

        for variacao in variacoes:
            estoque_insuficiente = True
            qtd_variacao_estoque = variacao.estoque
            qtd_carrinho = carrinho[str(variacao.id)]["quantidade"]
            preco_unitario = carrinho[str(variacao.id)]["preco_unitario"]
            preco_unitario_promo = carrinho[str(variacao.id)]["preco_unitario_promo"]

            if qtd_variacao_estoque < qtd_carrinho:
                carrinho[str(variacao.id)]["quantidade"] = qtd_variacao_estoque
                carrinho[str(variacao.id)]["preco"] = qtd_variacao_estoque * preco_unitario
                carrinho[str(variacao.id)]["preco_promo"] = qtd_variacao_estoque * preco_unitario_promo
        
        if estoque_insuficiente: 
            messages.error(self.request, "Quantidade de produtos do carrinho insuficiente, a quantidade foi substituida pela disponivel. ")
            self.request.session.save()
        
        qtd_total_carrinho = sum((cart["quantidade"] for cart in carrinho.values()))
        valor_total_carrinho = sum([item["preco_promo"] if item["preco_promo"] else item["preco"] for key,item in carrinho.items()])
        
      
        pedido = Pedido(
            user=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status="C"
        )
        pedido.save()
        ItemPedido.objects.bulk_create(
            [
                ItemPedido(**{"pedido":pedido, "produto":item["nome_produto"], "variacao":item["nome_variacao"], "id_variacao":item["id_variacao"], "preco_promo":item["preco_promo"], "preco":item["preco"], "quantidade":item["quantidade"], "imagem":item["img"] }) for item in carrinho.values()
            ]
        )
       
        """dict_pagar = {
            "qtd_total_carrinho":qtd_total_carrinho,
            "valor_total_carrinho":valor_total_carrinho
        }"""
        del self.request.session["carrinho"]
        
        return redirect(
            reverse('pagar-pedido', kwargs={'pk':pedido.pk}) 
        )
        #return render(self.request, self.template_name, dict_pagar)

class DetalhePedido(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = "pedido" 
    template_name = "pedido/detalhe.html"   
    pk_url_kwargs = "pk"

class ListaPedido(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = "pedidos"
    template_name = "pedido/lista_pedido.html"   
    paginate_by = 10
    ordering = ["-id"]

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}
{% load static %}
{% load omfilters %}

{% block conteudo %}
<div class="row">
    <div class="col">

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ pedido.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4"> {{ pedido.quantidade }} </div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ pedido.status|get_status }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th> 
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>
                {% for ped in pedido.itempedido_set.all %}
                    <tr>
                        <td class="d-none d-lg-block">
                            <img class="cart-img" src="{% get_media_prefix %}{{ ped.imagem }}">
                        </td>
                        <td>{{ ped.produto }}</td>
                        <td>{{ ped.variacao }}</td>
                        <td>{{ ped.quantidade }}</td>
                        <td>
                            {% if ped.preco_promo %}
                                {{ ped.preco_promo|formata_preco  }}
                            {% else %}
                                {{ ped.preco|formata_preco  }}
                            {% endif %}
                        </td>
                    </tr>
                
                {% endfor %}
                
            </table>
        </div>
    </div>
</div>

{% endblock  %}

pedido/templates/pedido/lista_pedido.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}
{% block conteudo %}
<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{ user }}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for pedido in pedidos %}
                <tr>
                    <th scope="row">Pedido N. {{pedido.pk}}</td>
                    <td>{{ pedido.total|formata_preco }}/td>
                    <td>{{ pedido.quantidade }} </td>
                    <td>{{ pedido.status|get_status }}</td>
                    <td>
                        <a href="{% url 'detalhe-pedido' pedido.pk %}" >
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}


            </table>
        </div>
    </div>
</div> 
<div class="row">
    <div class="col text-center">
        {% include 'paginacao/paginacao.html' %}
    </div>
</div>
{% endblock  %}

pedido/templates/pedido/pagar_pedido.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}
{% block conteudo %}
    <div class="row">
        <div class="col">
            <h3>Escolha o método de pagamento</h3>
            <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h3>{{ pedido }}</h3>

            <div class="row mt-4">
                <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
                <div class="col-lg-4">{{ pedido.id }}</div>
                <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
                <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>

                <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
                <div class="col-lg-4"> {{ pedido.quantidade }} </div>
                <div class="col-lg-2 font-weight-bold">Status:</div>
                <div class="col-lg-4">{{ pedido.status|get_status }}</div>
            </div>

            <div class="row mt-4">
                <div class="col">
                    <h3>Produtos</h3>
                </div>
            </div>

            <div class="table-responsive mt-3">
                <table class="table">
                    <tr>
                        <th class="d-none d-lg-block">Imagem</th>
                        <th>Produto</th>
                        <th>V.</th>
                        <th>QTD.</th>
                        <th>Total</th>
                    </tr>

                    {% for ped in pedido.itempedido_set.all %}
                        <tr>
                            <td class="d-none d-lg-block">
                                <img class="cart-img" src="{% get_media_prefix %}{{ ped.imagem }}">
                            </td>
                            <td>{{ ped.produto }}</td>
                            <td>{{ ped.variacao }}</td>
                            <td>{{ ped.quantidade }}</td>
                            <td>
                                {% if ped.preco_promo %}
                                    {{ ped.preco_promo|formata_preco  }}
                                {% else %}
                                    {{ ped.preco|formata_preco  }}
                                {% endif %}
                            </td>
                        </tr>
                    
                    {% endfor %}
                    
                </table>
            </div>


            <div class="row mt-4">
                <div class="col">
                    <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
                </div>
            </div>


        </div>
    </div>
{% endblock  %}