produto/urls.py
from django.urls import path, include
from .views import ListagemProduto, DetalheProduto, RemoverProduto, Carrinho, FinalizarCarrinho, AdicionarProduto, BuscaProduto

urlpatterns = [
    path("", ListagemProduto.as_view(), name="listagem-produto"), 
    path("carrinho/", Carrinho.as_view(), name="carrinho"),
    path("adicionar-carrinho/", AdicionarProduto.as_view(), name="adicionar-carrinho"),
    path("remover-carrinho/<int:id_variacao>/", RemoverProduto.as_view(), name="remover-carrinho"),
    path("finalizar-carrinho/", FinalizarCarrinho.as_view(), name="finalizar-carrinho"),
    path("<slug>/", DetalheProduto.as_view(), name="detalhe-produto"),
    path("busca", BuscaProduto.as_view(), name="busca-produto"),
]

produto/models.py
from django.db import models
from PIL import Image
from django.conf import settings
from django.utils.text import slugify
import os



class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    img = models.ImageField(upload_to='produto/',blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField()
    preco_marketing_promo = models.FloatField(default=0,)
    tipo = models.CharField(
        default="v",
        max_length=1,
        choices=
        (
            ("V", "Variação"),
            ("S", "Simples")
        )
    )

    @staticmethod
    def redimenciona_img(img, novo_tamanho = 800):
        path_completo = os.path.join(settings.MEDIA_ROOT,img.name)
        img_pil = Image.open(path_completo)
        largura_original,altura_original = img_pil.size

        if largura_original <= novo_tamanho:
            img_pil.close()
            return

        novo_tamanho = round(novo_tamanho * altura_original / largura_original)
        imagem_reduzida = img_pil.resize((largura_original, altura_original), Image.LANCZOS)
        imagem_reduzida.save(
            path_completo,
            optimize=True,
            quality=50
        )

    def save(self,*args,**kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug


        super().save(*args,**kwargs)
        if self.img:
            self.redimenciona_img(self.img, 800)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    produto = models.ForeignKey(Produto,on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promo = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = "Variação"
        verbose_name_plural = "Variações"

produto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from .models import Produto, Variacao
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.db.models import Q


class ListagemProduto(ListView):
    queryset = Produto.objects.all().order_by("id")
    context_object_name = "produtos"
    paginate_by = 10
    ordering = ["-id"]

class BuscaProduto(ListView):
    model = Produto
    context_object_name = "produtos"
    def get_queryset(self, *args, **kwargs):
        query = super().get_queryset(*args, **kwargs)
        termo = self.request.GET.get("termo") or self.request.session["termo"]
        if not termo:
            return query
        query = query.filter(Q(nome__contains=termo) | Q(descricao_curta__icontains=termo)  | Q(descricao_longa__icontains=termo)) 
        self.request.session.save()
        return query

class DetalheProduto(DetailView):
    queryset = Produto.objects.all()
    template_name = "produto/detalhe.html"
    slug_url_kwarg = 'slug'


class AdicionarProduto(View):
    def post(self, *args, **kwargs):
        qtd = 1

        # if self.request.session.get("carrinho"):
        #     del self.request.session["carrinho"]
        #     self.request.session.save()

        variacao_id = self.request.POST.get("vid")
        if not variacao_id.isnumeric():
            messages.error(self.request, "teste")
            return redirect(self.request.META["HTTP_REFERER"])


        variacao = get_object_or_404(Variacao, id=variacao_id)

        if variacao.estoque < 1:
            messages.error(self.request,"Produto não disponível em estoque !")
            return redirect(self.request.META["HTTP_REFERER"])

        if not self.request.session.get("carrinho"):
            self.request.session["carrinho"] = {}
            self.request.session.save()

        if "qtd" in self.request.POST:
            qtd = self.request.POST.get('qtd')


        carrinho = self.request.session["carrinho"]

        produto = variacao.produto
        if variacao_id in carrinho:
            qtd = carrinho[variacao_id]["quantidade"] + 1
            if variacao.estoque < qtd:
                messages.warning(self.request,f"Estoque insuficiente {qtd}x do produto {produto.nome}, mas foram adicionados {variacao.estoque}x em seu carrinho.")
            carrinho[variacao_id]["quantidade"] = variacao.estoque
            carrinho[variacao_id]["preco_promo"] = variacao.estoque * variacao.preco_promo
            carrinho[variacao_id]["preco"] = variacao.estoque * variacao.preco
            carrinho[variacao_id]["preco_unitario_promo"] = variacao.preco_promo
            carrinho[variacao_id]["preco_unitario"] = variacao.preco
        else:
            carrinho[variacao_id] = get_dict_carrinho(variacao, produto)

        messages.success(self.request,"Produto foi adicionado ao seu carrinho!")
        self.request.session["carrinho"] = carrinho
        return redirect(self.request.META["HTTP_REFERER"])


class RemoverProduto(ListView):
    def get(self,*args,**kwargs):
        try:
            if self.request.session.get("carrinho"):
                del self.request.session["carrinho"][str(kwargs["id_variacao"])]
                self.request.session.save()

            if str(kwargs["id_variacao"]) not in self.request.session["carrinho"]:
                messages.success(self.request, "Produto removido do carrinho, o seu carrinho ficou vazio, adicione algo ao carrinho !")
                return redirect("listagem-produto")
            messages.success(self.request, "Produto removido do carrinho !")
        except Exception as e:
            print(e)
            messages.error(self.request, "Ocorreu um erro ao remover o produto do carrinho!")
        return redirect(self.request.META["HTTP_REFERER"])

class Carrinho(ListView):
    def get(self, *args, **kwargs):
        carrinho = self.request.session.get("carrinho", {})
        return render(self.request, "produto/carrinho.html",{"carrinho":carrinho})


class FinalizarCarrinho(View): 
    @method_decorator(login_required(login_url='/login/')) 
    def get(self, request, *args, **kwargs):

        if not self.request.session.get("carrinho"):
            messages.error(
                self.request,
                "Seu carrinho está vazio."
            )
            return redirect(reverse_lazy("listagem-produto"))

        dict_finalizar_carrinho = {
            "usuario": self.request.user,
            "carrinho": self.request.session["carrinho"]
        }
        return render(request, "produto/finalizar_carrinho.html", dict_finalizar_carrinho)
    

def get_dict_carrinho(variacao, produto):
    return {"img":produto.img.name ,"quantidade":1, "preco_promo":variacao.preco_promo, "preco":variacao.preco,"nome_variacao":variacao.nome,"preco_unitario_promo":variacao.preco_promo,"preco_unitario":variacao.preco,"id_variacao":variacao.pk,"nome_produto":produto.nome,"slug":produto.slug}

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}
{% block conteudo %}


<main class="container mt-4 mb-4">
    {% include 'mensagem/mensagem.html' %}
    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            {% include 'tabelas/tabela_produtos.html' %} 
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{carrinho|valor_total_carrinho|formata_preco}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            {% if request.user.is_authenticated %}
                <a class="btn btn-lg btn-block btn-primary" href="{% url 'finalizar-carrinho' %}">
                    Finalizar a compra
                </a>
            {% else %}
                 <a class="btn btn-lg btn-block btn-primary" href="{% url 'login' %}">
                    Logar
                </a>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo %}

<main class="container mt-4 mb-4">
    {% include 'mensagem/mensagem.html' %}
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg">
                    <div class="row no-gutters">
                        <div class="col-lg-12">
                            {% if produto.img %}
                                <img class="img-fluid" src="{{produto.img.url}}" alt="produto.nome">
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg">
                    <div class="mt-4 mt-lg-0">
                        <h1 class="h2">{{ produto.nome }}!</h1>
                        <p class="lead">{{ produto.descricao_curta}}</p>
                        <p class="lead">
                            {% if produto.preco_marketing_promo %}
                                <span id="variation-preco" class="lead product-price">R$ {{produto.preco_marketing_promo |formata_preco}}</span>
                                <span id="variation-preco-promocional"
                                    class="lead product-old-price text-muted">R$ {{produto.preco_marketing|formata_preco}} </span>
                            {% else  %}
                                <span id="variation-preco" class="lead product-price">R$ {{produto.preco_marketing|formata_preco}}</span>
                            {% endif %}
                        </p>
                        <form action="{% url 'adicionar-carrinho' %}" id="form-add-to-cart" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                    {% for variacao in produto.variacao_set.all %}
                                        <option data-preco="R$ {{variacao.preco|formata_preco}}" data-preco-promocional="R$ {{variacao.preco_promo|formata_preco}}" value="{{variacao.id}}">
                                            {{ variacao.nome }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="text-left">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    Adicionar ao carrinho
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="mt-5 mb-5">
                        <h2 class="text-center">{{ produto.nome }} </h2>
                        <p>
                            {{ produto.descricao_longa|linebreaks }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
{% endblock %}

produto/templates/produto/finalizar_carrinho.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo  %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil' %}">clique aqui</a></p>
        <div class="row">
            <div class="col-lg-2">Nome:</div>
            <div class="col-lg-4">{{ usuario.first_name }}</div>
            <div class="col-lg-2">Sobrenome:</div>
            <div class="col-lg-4">{{ usuario.last_name }}</div>

            <div class="col-lg-2">Idade:</div>
            <div class="col-lg-4">{{ usuario.perfil.idade }}</div>
            <div class="col-lg-2">Nascimento:</div>
            <div class="col-lg-4">{{ usuario.perfil.data_nascimento }}</div>

            <div class="col-lg-2">CPF:</div>
            <div class="col-lg-4">{{ usuario.perfil.cpf }}</div>
            <div class="col-lg-2">E-mail:</div>
            <div class="col-lg-4">{{ usuario.email }}</div>
        </div>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'perfil' %}">clique aqui</a></p>
        <div class="row">
            <div class="col-lg-2">Endereço:</div>
            <div class="col-lg-4">{{ usuario.perfil.endereco }}</div>
            <div class="col-lg-2">Número:</div>
            <div class="col-lg-4">{{ usuario.perfil.numero }}</div>

            <div class="col-lg-2">Complemento:</div>
            <div class="col-lg-4">{{ usuario.perfil.complemento }}</div>
            <div class="col-lg-2">Nascimento:</div>
            <div class="col-lg-4">{{ usuario.perfil.bairro }}</div>

            <div class="col-lg-2">Cidade:</div>
            <div class="col-lg-4">{{ usuario.perfil.cidade }}</div>
            <div class="col-lg-2">Estado:</div>
            <div class="col-lg-4">{{ usuario.perfil.estado }}</div>

            <div class="col-lg-2">CEP:</div>
            <div class="col-lg-4">{{ usuario.perfil.cep }}</div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'tabelas/tabela_produtos.html' %} 
    </div>
</div>

<div class="row">
    <div class="col">
        <h3>
            Total Carrinho: {{ carrinho|valor_total_carrinho|formata_preco }}
        </h3>
    </div>
</div

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'finalizar-pedido' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>

{% endblock  %}

produto/templates/produto/produto_list.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo %}

<main class="container mt-4 mb-4">
    <main class="container mt-4 mb-4">
        {% include 'mensagem/mensagem.html' %}
        <div class="row">
            <div class="col-lg-12">
                <div class="card-columns">
                    {% for produto in produtos %}
                        <div class="card">
                            {% if produto.img %}
                                <a href="{{ produto.slug }}">
                                    <img class="card-img-top" src="{{ produto.img.url }}" alt="{{ produto.nome }}">
                                </a>
                            {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ produto.nome }}</h5>
                            <p class="card-text">{{produto.descricao_curta}}</p>
                            <div class="container product-price-block text-center">
                                {% if produto.preco_marketing %}
                                    <span class="produt-price">
                                        {{ produto.preco_marketing_promo|formata_preco }}
                                    </span>
                                    <span class="product-old-price text-muted">
                                       {{ produto.preco_marketing|formata_preco }}
                                    </span>
                                {% else %}
                                    <span class="product-old-price text-muted">
                                        {{ produto.preco_marketing|formata_preco }}
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{{ produto.slug }}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                    {% empty %}
                    <div>
                        sem produtos
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-center">
                {% include './paginacao/paginacao.html' %}
            </div>
        </div>
    </main>

</main>
{% endblock %}